a = input ('Digite algo: ')
print ('o tipo primitivo desse algo é:', type(a))
print ('Só tem espaço?', a.isspace())
print ('é um numero? ', a.isnumeric())
print ('É alfabético? ', a.isalpha())
print ('É alpha numerico? ', a.isalnum())
print ('Esta em maiusculas?', a.isupper())
print ('Esta em minuscula?', a.islower())
print ('Está capitalizada? ', a.istitle())
